6
alexross2502/coolserver pull request #14
Opened 2023-03-13 10:19 UTC by alexross2502

2023-03-13 15:35 UTC, nik-clockwise requested changes

2023-03-13 15:35 UTC, nik-clockwise commented on .gitignore
> +config
Там у нас что?

2023-03-13 15:35 UTC, nik-clockwise commented on controllers/reservationController.js
> +      let end = new Date(+day + timeSize[size] * 3600 * 1000).toString(
не надо, toString, должно работать так (с Date)

2023-03-13 15:35 UTC, nik-clockwise commented on migrations/20230307132822-deleteHoursAddEnd.js
> +    await QueryInterface.addColumn("reservations", "end", {
А что с существующими резервациями? Нужно мигрировать так, что бы данные не постарадли (задача со звездочкой)

2023-03-14 07:28 UTC, alexross2502 commented on .gitignore
> +config
там доступы к базе для миграции, она их требует

2023-03-15 11:22 UTC, nik-clockwise approved these changes

2023-03-15 11:23 UTC, merged