add: typescript
alexross2502/coolserver pull request #25
Opened 2023-03-22 09:41 UTC by alexross2502

2023-03-22 12:09 UTC, nik-clockwise requested changes
Глобально: надо сгруппировать все ts и рабочие файлы проекта в подпапку src - это муветон, так принято делать. Соответственно, когда у тебя будет собран билд, то будет две папки /build или /dist (как назовешь) и /src с исходниками. Так и импоры всякие "тяжелые" (бывает sequelize ругается) легче делать просто папка dist или src будет

2023-03-22 12:09 UTC, nik-clockwise commented on controllers/adminController.ts
> +      bcrypt.compare(
А давай сделаем как это черзе async await и вынесем эту функцию в какой-то auth service что бы можно было делать так auth.login(login, pass) и вернуть объект с токеном.

2023-03-22 12:09 UTC, nik-clockwise commented on controllers/adminController.ts
> +                availability: true,
Непонятно для это надо (availability)

2023-03-22 12:09 UTC, nik-clockwise commented on controllers/adminController.ts
> +    return res.status(400).json({ message: e }).end();
Сделать бы так что бы мы резолвили 400 статус в одном месте, вместо 3х. Ну и 200 тоже в одном

2023-03-22 12:09 UTC, nik-clockwise commented on controllers/adminController.ts
> +        return res.status(400).json({ message: "error" }).end();
надо как-то поубирать эту лапшу со всех контроллеров в виде else 400 catch 400 else 400
Вполне достаточно catch

2023-03-22 12:09 UTC, nik-clockwise commented on controllers/reservationController.ts
> +let timeSize = {
надо вынести куда-то в constants.ts параметры такого плана, что бы были в одном месте для всего проекта. А то потеряется в контроллере и всё такое

2023-03-22 12:09 UTC, nik-clockwise commented on db.ts
> +  process.env.DB_DATABASE,
у нас все эти настройки есть в config.ts, нуноих оттуда взять

2023-03-22 12:09 UTC, nik-clockwise commented on db.ts
> +  process.env.DB_DATABASE,
А еще лучше создать какой-то  db.config в котором создать весь объект, который вставляется в new Serquelize

2023-03-22 12:09 UTC, nik-clockwise commented on middleware/passport.ts
> +        done: (arg0: any, arg1: boolean | Admin) => void
Странные arg0 arg1, надо бы хоть назвать человекопонятно

2023-03-22 12:09 UTC, nik-clockwise commented on models/Masters.ts
> +  public townId!: typeof DataTypes.UUID;
тут у тебя nullable поле, так что надо ? ставить. Пройдись везде глянь, что б консистентно выглядели типы

2023-03-22 12:09 UTC, nik-clockwise commented on tsconfig.json
> +    "allowJs": true,
Было бы хорошо allowJs false сделать, если будет работать - то супер. Если будет ссылаться куда-то глубоко, то фиг с ним. У тебя ж в проекте (которые билдятся) все файлы ts уже, js не должн остаться

2023-03-22 13:27 UTC, alexross2502 commented on controllers/adminController.ts
> +      bcrypt.compare(
по глобальному: 
все в папке src, после транспиляции остается папка dist с результатом действия, папка src с исходниками .ts, и папка node_modules, в корне только package, ignore и tsconfig
Если все правильно, то на фронте такую же структуру делать?

2023-03-22 13:30 UTC, alexross2502 commented on controllers/adminController.ts
> +                availability: true,
Это изначально была такая реализация проверки авторизации админа, потом добавился jwt, который тоже нужно отослать на клиент и ответ превратился в объект с 2 свойствами

2023-03-22 13:31 UTC, alexross2502 commented on tsconfig.json
> +    "allowJs": true,
были миграции .js. Поменял, allowJs убрал, пока работает

2023-03-23 07:37 UTC, alexross2502 commented on db.ts
> +  process.env.DB_DATABASE,
все, связанное с process.env, находится только в config.ts. Из него уже берутся нужные поля и объекты и вставляются в new sequelize. Заодно и проблема с переменными окружения решилась, которая была, до этого все работало только с кредами в явном виде

2023-03-23 08:07 UTC, alexross2502 commented on controllers/reservationController.ts
> +let timeSize = {
constants.ts вынес в utils + там же сделал файл для функции с отправкой письма, она тоже в контроллере место занимала

2023-03-23 08:16 UTC, alexross2502 commented on middleware/passport.ts
> +        done: (arg0: any, arg1: boolean | Admin) => void
убрал, оно туда вообще случайно попало

2023-03-23 08:27 UTC, alexross2502 commented on controllers/adminController.ts
> +    return res.status(400).json({ message: e }).end();
убрал

2023-03-23 08:28 UTC, alexross2502 commented on controllers/adminController.ts
> +        return res.status(400).json({ message: "error" }).end();
убрал

2023-03-23 10:05 UTC, alexross2502 commented on models/Masters.ts
> +  public townId!: typeof DataTypes.UUID;
поменял на вопросы тут и в моделе с резервами 3 поля были allowNull:true

2023-03-23 14:41 UTC, alexross2502 commented on controllers/adminController.ts
> +      bcrypt.compare(
по auth.login(login, pass) - готово

2023-03-24 09:59 UTC, nik-clockwise requested changes

2023-03-24 09:59 UTC, nik-clockwise commented on src/controllers/adminController.ts
> +      auth
ну рас уж у нас в проекте много юзается async/await, то надо стараться его везде использовать, что бы всё было  одном стиле (прям всё переделывать не надо, но тут можно)

2023-03-24 09:59 UTC, nik-clockwise commented on src/utils/constants.ts
> +export let timeSize = {
const т.к. мы не переопределяем эту переменную в дальнейшем, она статическая

2023-03-24 09:59 UTC, nik-clockwise commented on src/utils/sendMail.ts
> +    host: process.env.POST_HOST,
для этого тоже можно отдельный конфиг создать и сда уже просто конфиг вставить

2023-03-24 10:14 UTC, alexross2502 commented on src/controllers/adminController.ts
> +      auth
готово

2023-03-24 10:14 UTC, alexross2502 commented on src/utils/constants.ts
> +export let timeSize = {
готово

2023-03-24 10:25 UTC, alexross2502 commented on src/utils/sendMail.ts
> +    host: process.env.POST_HOST,
готово

2023-03-24 10:44 UTC, nik-clockwise requested changes

2023-03-24 10:44 UTC, nik-clockwise commented on src/controllers/adminController.ts
> +          await auth.login(login, password, availability.dataValues.password)
О_О

2023-03-24 10:44 UTC, nik-clockwise commented on src/controllers/adminController.ts
> +          await auth.login(login, password, availability.dataValues.password)
НЕ надо так, потмоу что совсем не читается


const authTokens = await auth.login
res.json(authTokens)

2023-03-24 10:44 UTC, nik-clockwise commented on src/utils/sendMail.ts
> +    from: transporterCredentials.auth.user,
Тут наверно default можно установить в конфиге и будет работать для всех from по умолчанию

2023-03-24 10:51 UTC, alexross2502 commented on src/controllers/adminController.ts
> +          await auth.login(login, password, availability.dataValues.password)
просто я где-то слышал, что если есть возможность не создавать переменную, то лучше не создавать. Типа оптимизация затрат памяти. Переделал

2023-03-24 11:08 UTC, alexross2502 commented on src/utils/sendMail.ts
> +    from: transporterCredentials.auth.user,
убрал совсем это, оно там не обязательно было

2023-03-24 11:11 UTC, alexross2502 commented on src/controllers/adminController.ts
> +          await auth.login(login, password, availability.dataValues.password)
переменную создал и ее потом в res.json засунул

2023-03-27 09:52 UTC, nik-clockwise commented on src/controllers/adminController.ts
> +          await auth.login(login, password, availability.dataValues.password)
Не в нашем случае, лучше читаемость чем одна переменная со строкой

2023-03-27 11:26 UTC, merged