Registration
alexross2502/coolserver pull request #31
Opened 2023-04-05 15:21 UTC by alexross2502

2023-04-05 15:36 UTC, nik-clockwise requested changes

2023-04-05 15:36 UTC, nik-clockwise commented on src/models/Masters.ts
> +    email: {type: DataTypes.CHAR(36), allowNull: false, unique: true}
А ту тнам не нужен email, он же есть у нас в users?

2023-04-05 15:36 UTC, nik-clockwise commented on src/utils/createNewClient.ts
> +    await Clients.create({
А как система понимает что новый user это какой-то клиент или мастер?

2023-04-05 15:36 UTC, nik-clockwise commented on src/utils/reservationDuplication.ts
>    return duplication.length;
Тут кстати так не годится, зачем на выбирать ALL (потенциально могут быть миллионы) в память, если мы хотим узнать количество? В БД есть методы для аггрегаций и подсчета результатов

2023-04-05 15:44 UTC, alexross2502 commented on src/models/Masters.ts
> +    email: {type: DataTypes.CHAR(36), allowNull: false, unique: true}
в моей реализации email - единственное, что связывает мастеров с masters и его учетку с users

2023-04-05 15:46 UTC, alexross2502 commented on src/utils/createNewClient.ts
> +    await Clients.create({
они все связаны по email. Создается новый мастер или клиент и вместе с ним связка логин-пароль-роль его, при удалении все то же самое, но в обратном порядке

2023-04-07 08:37 UTC, nik-clockwise requested changes

2023-04-07 08:37 UTC, nik-clockwise commented on src/controllers/mastersController.ts
> +    await Users.destroy({ where: { login: master.dataValues.email } });
Давай сделаем каскадное удаление для юзеров, если удален мастер или клиент (или админ?)

2023-04-07 09:43 UTC, merged