Authorization
alexross2502/coolserver pull request #34
Opened 2023-04-11 14:29 UTC by alexross2502

2023-04-11 15:25 UTC, nik-clockwise requested changes

2023-04-11 15:25 UTC, nik-clockwise commented on src/controllers/clientsController.ts
> +const jwt = require("jsonwebtoken");
У нас typescript, нужно везде использовать импорты

2023-04-11 15:25 UTC, nik-clockwise commented on src/controllers/clientsController.ts
> +    const token = req.headers.authorization.split(" ")[1];
Все проверки токенов можем вынести в middleware

2023-04-11 15:25 UTC, nik-clockwise commented on src/controllers/clientsController.ts
> +    const clientId = jwt.verify(token, "dev-jwt").id;
а после успешного прохождения аутентификации в middleware принятно вставлять текущего юзера в request для текущего запроса и оттуда уже получать user id и работать с ним

2023-04-11 15:25 UTC, nik-clockwise commented on src/controllers/mastersController.ts
> +    const token = req.headers.authorization.split(" ")[1];
Дубли

2023-04-11 15:25 UTC, nik-clockwise commented on src/middleware/passport.ts
Нам нужен этот файл, зачем его удалять?

2023-04-11 15:25 UTC, nik-clockwise commented on src/utils/auth.ts
> +  async login(login: string, userPassword: string, adminPassword: string, role: string, id: string) {
Не понятно что за adminPassword, не читаемо, нужно как-то переименовать это всё, что бы можно было понять что происходит

2023-04-11 15:25 UTC, nik-clockwise commented on src/utils/createNewClient.ts
> +      id: availability.dataValues.id,
Автогенерация была раньше, зачем её удалять, это же удобно

2023-04-11 15:25 UTC, nik-clockwise commented on src/middleware/roleMiddleware.ts
> +      const userRole = jwt.verify(token, "dev-jwt").role;
слишком много jwt.verify в проекте. Можно сделать это в одном месте, а дальше уже использовать аутентифицированного юзера для текущего запроса

2023-04-12 09:07 UTC, alexross2502 commented on src/utils/createNewClient.ts
> +      id: availability.dataValues.id,
решили оставить

2023-04-12 09:20 UTC, alexross2502 commented on src/middleware/passport.ts
вернул

2023-04-12 09:25 UTC, alexross2502 commented on src/utils/auth.ts
> +  async login(login: string, userPassword: string, adminPassword: string, role: string, id: string) {
переименовал

2023-04-12 10:46 UTC, alexross2502 commented on src/controllers/clientsController.ts
> +    const clientId = jwt.verify(token, "dev-jwt").id;
+

2023-04-12 10:46 UTC, alexross2502 commented on src/controllers/clientsController.ts
> +    const token = req.headers.authorization.split(" ")[1];
+

2023-04-12 10:47 UTC, alexross2502 commented on src/controllers/clientsController.ts
> +const jwt = require("jsonwebtoken");
+

2023-04-12 10:47 UTC, alexross2502 commented on src/controllers/mastersController.ts
> +    const token = req.headers.authorization.split(" ")[1];
+

2023-04-12 10:49 UTC, alexross2502 commented on src/middleware/roleMiddleware.ts
> +      const userRole = jwt.verify(token, "dev-jwt").role;
только в roleMiddleware оставил

2023-04-12 11:30 UTC, nik-clockwise requested changes

2023-04-12 11:30 UTC, nik-clockwise commented on src/controllers/clientsController.ts
> +    if (!req.user) {
твой авторизационный middleware гарантирует то что в req.user будет то что ты ожидаешь, по этому дальше уже не нужно делать никаких проверок на этот счет, лишний код получается

2023-04-12 11:30 UTC, nik-clockwise commented on src/middleware/roleMiddleware.ts
> +      req.user = payloadFromToken;
Этот middleware у нас занимается только проверкой роли на соответствие требуемой. Нужно разделять логику, и не мешать всё в кучу иначе потом будет очень тяжело и плохо в этом всем разбираться. 

Функции, компоненты, классы долны выполнять одну задачу, а если выполняет больше - это признак того что нужно разделить это на 2 или больше частей. Можешь в гугле об этом поискать что-то

2023-04-12 11:30 UTC, nik-clockwise commented on src/routes/clientsRouter.ts
> +  [passport.authenticate("jwt", { session: false }), roleMiddleware(["admin"])],
можно попробовать объединить эти два middelware в новый вызвав один потом другой, так будет всё более компактно. Если хочешь можешь сделать

2023-04-12 12:49 UTC, alexross2502 commented on src/controllers/clientsController.ts
> +    if (!req.user) {
+

2023-04-12 13:03 UTC, alexross2502 commented on src/middleware/roleMiddleware.ts
> +      req.user = payloadFromToken;
разделил на проверку наличия прав доступа и проверку наличия токена и декодирование его содержимого

2023-04-12 13:05 UTC, alexross2502 commented on src/routes/clientsRouter.ts
> +  [passport.authenticate("jwt", { session: false }), roleMiddleware(["admin"])],
собрал в один разделенный на прошлом єтапе middleware. С паспортом немного повозился, но он так просто не дается, его потом попробую в тот же combinedMiddleware засунуть

2023-04-13 09:05 UTC, merged