Statusandprice
alexross2502/coolserver pull request #38
Opened 2023-04-20 13:28 UTC by alexross2502

2023-04-20 14:56 UTC, nik-clockwise requested changes
Проект разрастается, нужно настроить линтер и/или притиер и настроить его таким образом что бы он работал всегда (после сохранения редактируемого файла).

2023-04-20 14:56 UTC, nik-clockwise commented on src/controllers/clientsController.ts
> +  const whereOptions: Iwhere = {};
where в где-то есть в sequelize в виде generic типа кажется, сам понимает что есть в model и то можно менять. Попробуй поискать

2023-04-20 14:56 UTC, nik-clockwise commented on src/interfaces/interfaces.ts
> +export class Iwhere {
interfaces/interfaces Iwhere - mastre_id - выглядит буд-то это для всего приложения интерфейс, но master_id нас только у мастеров. Вобщем нужно что-то более осмысленное с этим сделать

2023-04-20 14:56 UTC, nik-clockwise commented on src/models/Reservation.ts
> +      defaultValue: "confirmed",
я бы добавил статус new для новых заказов, а confirmed похоже на то, что кто-то (мастер/админ) увидел заказ и начал его обабатывать

2023-04-20 14:56 UTC, nik-clockwise commented on src/models/Towns.ts
> +  public tariff!: typeof DataTypes.INTEGER;
туриф у нас по городам или по мастерам в городах? Мне кажется логичней сделать тариф для каждого мастера в конкретном городе свой. Но тут уже зависит от того как задача поставлена

2023-04-20 14:56 UTC, nik-clockwise commented on src/routes/clientsRouter.ts
> +  "/:confirmation?",
Вопрос значит что не обязательный параметр?

2023-04-20 14:56 UTC, nik-clockwise commented on src/utils/decodingToken.ts
Надо бы поменять название, не принято называть файлы, класы, переменные и всё подоброе глаголами. Почитай что-то на эту тему

2023-04-20 14:56 UTC, nik-clockwise commented on src/utils/priceCalculation.ts
> +  const town = await Towns.findOne({
В такого рода функцию лучше уже передавать полученный в другом месте город или даже просто тариф (number) и таким образом изолировать функцию от лишних зависимостей

2023-04-21 08:04 UTC, alexross2502 commented on src/models/Reservation.ts
> +      defaultValue: "confirmed",
+

2023-04-21 08:05 UTC, alexross2502 commented on src/models/Towns.ts
> +  public tariff!: typeof DataTypes.INTEGER;
+

2023-04-21 08:05 UTC, alexross2502 commented on src/routes/clientsRouter.ts
> +  "/:confirmation?",
+

2023-04-21 08:23 UTC, alexross2502 commented on src/routes/clientsRouter.ts
> +  "/:confirmation?",
убрал его вообще

2023-04-21 08:23 UTC, alexross2502 commented on src/models/Towns.ts
> +  public tariff!: typeof DataTypes.INTEGER;
решили оставить

2023-04-21 08:23 UTC, alexross2502 commented on src/models/Reservation.ts
> +      defaultValue: "confirmed",
решили оставить

2023-04-21 08:25 UTC, alexross2502 commented on src/utils/decodingToken.ts
переименовал, почитаю на выходных об єтом подробнее

2023-04-21 08:30 UTC, alexross2502 commented on src/utils/priceCalculation.ts
> +  const town = await Towns.findOne({
убрал запрос в базу из функции

2023-04-21 09:04 UTC, alexross2502 commented on src/interfaces/interfaces.ts
> +export class Iwhere {
удалил

2023-04-21 09:21 UTC, alexross2502 commented on src/controllers/clientsController.ts
> +  const whereOptions: Iwhere = {};
генерики нашел, но там что-то слишком непонятное. На выходных заведу отдельный ПР и добавлю правильные генерики, пока просто интерфейс в моделе создал, а папку с интерфейсами удалил

2023-04-21 13:22 UTC, alexross2502 commented on src/controllers/clientsController.ts
> +  const whereOptions: Iwhere = {};
+

2023-04-24 11:58 UTC, nik-clockwise approved these changes

2023-04-24 11:58 UTC, nik-clockwise commented on src/models/Clients.ts
> +export type ClientsWhereOptions = WhereOptions & {
А тут нет generic типа WhereOptions<ModelName> ?

2023-04-24 12:18 UTC, merged