Cloudinary and pagination
alexross2502/coolserver pull request #42
Opened 2023-05-01 12:34 UTC by alexross2502

2023-05-02 14:24 UTC, nik-clockwise requested changes

2023-05-02 14:24 UTC, nik-clockwise commented on src/controllers/reservationController.ts
> +require("dotenv").config();
Это нам тут не нужно, у нас же уже всё засетаплено в точке входа

2023-05-02 14:24 UTC, nik-clockwise commented on src/controllers/reservationController.ts
> +    cloudinary.uploader.destroy(`${el.dataValues.public_id}`);
Если это асинхронная функция (а она должна быть такой), то не все картинки могут удалиться. Нужно дождаться конца удаления

2023-05-02 14:24 UTC, nik-clockwise commented on src/controllers/reservationController.ts
>    const reservation = await Reservation.destroy({ where: { id: id } });
А если будет ошибка при удалении картинки, что будет с заказом? Надо бы транзакцию использовать

2023-05-02 14:24 UTC, nik-clockwise commented on src/controllers/reservationController.ts
> +        images: image.length !== 0,
это что не понятно

2023-05-02 14:24 UTC, nik-clockwise commented on src/controllers/reservationController.ts
> +          const imageBinary = base64Img.imgSync(image[i].img, "", `png`);
А если кто-то загрузит webp или tiff картинку, что с расширением будет?

2023-05-02 14:24 UTC, nik-clockwise commented on src/migrations/20230308135263-cloudinary.ts
> +      type: DataTypes.BOOLEAN,
нам не нужны никакие пометки в заказах о картинках, это денормализация данных получается

2023-05-02 14:24 UTC, nik-clockwise commented on package.json
> +    "multer": "^1.4.5-lts.1",
Не видел где мы юзаем multer, а лучше его юзать

2023-05-04 06:48 UTC, alexross2502 commented on package.json
> +    "multer": "^1.4.5-lts.1",
сначала думал, что он для удаления фото обязателен, удалил

2023-05-04 06:50 UTC, alexross2502 commented on src/controllers/reservationController.ts
> +require("dotenv").config();
+

2023-05-04 06:52 UTC, alexross2502 commented on src/controllers/reservationController.ts
> +    cloudinary.uploader.destroy(`${el.dataValues.public_id}`);
await +

2023-05-04 09:56 UTC, alexross2502 commented on src/controllers/reservationController.ts
>    const reservation = await Reservation.destroy({ where: { id: id } });
транзакцию подключил. Не знаю, как инсценировать нормально ошибку удаления фото в клаудинари, так что тестировал с нерабочим api_key, так, вроде, работает как надо. Если ловится ошибка на єтапе удаления фото - попадает в catch, где откат происходит и восстанавливаются записи в таблице с резервами и фото

2023-05-04 11:21 UTC, alexross2502 commented on src/controllers/reservationController.ts
> +          const imageBinary = base64Img.imgSync(image[i].img, "", `png`);
на клиенте присутствовала соответствующая проверка. Добавил и на сервере + транзакция для удаления заказа, которые должны создаваться раньше работы с картинками

2023-05-04 19:06 UTC, alexross2502 commented on src/controllers/reservationController.ts
> +        images: image.length !== 0,
убрал в контексте другого комментария

2023-05-04 19:08 UTC, alexross2502 commented on src/migrations/20230308135263-cloudinary.ts
> +      type: DataTypes.BOOLEAN,
убрал с резервов обычное поле, добавил VIRTUAL, логику, которая мне на клиент возвращала информацию - есть ли закрепленные фото за резервом, сделал через атрибуты findAll и sequelize.literal

2023-05-05 07:46 UTC, nik-clockwise requested changes

2023-05-05 07:46 UTC, nik-clockwise commented on src/controllers/reservationController.ts
> +      attributes: ["public_id"],
Это действие получается вне транзакции, могут быть ошибки и не правильное поведение

2023-05-05 07:46 UTC, nik-clockwise commented on src/controllers/reservationController.ts
>      let clientId = await check(clientName, recipient);
действие вне транзакции ,будут ошибки

2023-05-05 07:46 UTC, nik-clockwise commented on src/controllers/reservationController.ts
>        (await reservationDuplicationCheck(towns_id, master_id, start, end)) === 0
нет транзакции

2023-05-05 07:46 UTC, nik-clockwise commented on src/controllers/reservationController.ts
>          attributes: ["tariff"],
транзакция

2023-05-05 07:46 UTC, nik-clockwise commented on src/controllers/reservationController.ts
> +          await Images.create({
нет транзакции

2023-05-05 07:46 UTC, nik-clockwise commented on src/controllers/reservationController.ts
>        const town = await Towns.findOne({
транзакция

2023-05-05 07:46 UTC, nik-clockwise commented on src/migrations/20230308135263-cloudinary.ts
> +      type: DataTypes.VIRTUAL,
виртуальные колонки вроде не доабвляются в базу?

2023-05-05 09:33 UTC, alexross2502 commented on src/migrations/20230308135263-cloudinary.ts
> +      type: DataTypes.VIRTUAL,
+

2023-05-05 09:35 UTC, alexross2502 commented on src/controllers/reservationController.ts
> +      attributes: ["public_id"],
+

2023-05-05 09:39 UTC, alexross2502 commented on src/controllers/reservationController.ts
>      let clientId = await check(clientName, recipient);
передал транзакцию в функцию

2023-05-05 09:43 UTC, alexross2502 commented on src/controllers/reservationController.ts
>      let clientId = await check(clientName, recipient);
ROLLBACK работает, если ошибка возникает

2023-05-05 09:47 UTC, alexross2502 commented on src/controllers/reservationController.ts
>        (await reservationDuplicationCheck(towns_id, master_id, start, end)) === 0
передал, но как проверить не знаю. Не могу придумать какие ошибки могуть возникнуть на єтапе model.count(), чтоб их смоделировать

2023-05-05 09:49 UTC, alexross2502 commented on src/controllers/reservationController.ts
>          attributes: ["tariff"],
тоже передал, ошибку не могу придумать

2023-05-05 09:52 UTC, alexross2502 commented on src/controllers/reservationController.ts
> +          await Images.create({
передал, проверил

2023-05-05 09:54 UTC, alexross2502 commented on src/controllers/reservationController.ts
>        const town = await Towns.findOne({
+

2023-05-05 10:03 UTC, nik-clockwise approved these changes

2023-05-05 10:08 UTC, merged