PRRR
alexross2502/coolserver pull request #49
Opened 2023-05-05 11:16 UTC by alexross2502

2023-05-05 11:49 UTC, nik-clockwise requested changes

2023-05-05 11:49 UTC, nik-clockwise commented on src/controllers/clientsController.ts
> +    whereOptionsParser({
обычно order это не where и отделяется от where

2023-05-05 11:49 UTC, nik-clockwise commented on src/utils/whereOptionsParser.ts
> +    const sortedModel = sequelize.model(params.sortedField);
если в sortedField или sortingOrder передать "что угодно" будет ошибка?

2023-05-05 13:20 UTC, alexross2502 commented on src/utils/whereOptionsParser.ts
> +    const sortedModel = sequelize.model(params.sortedField);
теперь будет

2023-05-05 13:26 UTC, alexross2502 commented on src/controllers/clientsController.ts
> +    whereOptionsParser({
идея в том, чтоб передавать options и его же и получать обратно после обработки вместе со всеми настройками для запроса в базу. Так не подходит? Если речь о названии функции, то переименовал

2023-05-08 08:41 UTC, nik-clockwise approved these changes

2023-05-08 08:41 UTC, nik-clockwise commented on src/controllers/reservationController.ts
> +            "(SELECT id FROM images WHERE reservation_id = reservations.id LIMIT 1)"
это не join но пусть уже так будет, вообще не ок

2023-05-08 08:47 UTC, merged